name: Deploy Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - staging

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build Website
        run:
          nix build .#default

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        if: github.ref == '/refs/heads/main'
        with:
          path: './result'

      - name: Deploy Pages
        uses: actions/deploy-pages@v4
        if: github.ref == '/refs/heads/main'
